# ProjectFlow AI - Production Deployment Configuration

apiVersion: v1
kind: ConfigMap
metadata:
  name: projectflow-config
  namespace: production
data:
  # Application Configuration
  APP_NAME: "ProjectFlow AI"
  APP_VERSION: "1.0.0"
  ENVIRONMENT: "production"
  DEBUG_MODE: "false"
  
  # Claude AI Configuration
  USE_DEMO_MODE: "false"
  CLAUDE_BASE_URL: "https://api.anthropic.com/v1"
  CLAUDE_MODEL: "claude-3-5-sonnet-20241022"
  CLAUDE_VERSION: "2023-06-01"
  
  # Firebase Configuration
  FIREBASE_PROJECT_ID: "projectflow-1e82a"
  FIREBASE_AUTH_DOMAIN: "projectflow-1e82a.firebaseapp.com"
  FIREBASE_STORAGE_BUCKET: "projectflow-1e82a.firebasestorage.app"
  
  # Analytics and Monitoring
  ENABLE_ANALYTICS: "true"
  ENABLE_CRASHLYTICS: "true"
  
  # Network Configuration
  CONNECTION_TIMEOUT: "30000"
  RECEIVE_TIMEOUT: "30000"
  SEND_TIMEOUT: "30000"

---
apiVersion: v1
kind: Secret
metadata:
  name: projectflow-secrets
  namespace: production
type: Opaque
data:
  # Base64 encoded secrets
  # Use: echo -n "your-secret" | base64
  CLAUDE_API_KEY: c2stYW50LWFwaTAzLUk0N1B2MUFnV3p4aExhS2hZRzQ1bDhibjBoSzZ2WXZ1UmE2WWY0UWRIOEgyZXREQlNFNmhvTG0zSTZzYkk3U0dkaDdXY1FsckNUSHQ1Y3ZPSUxnTURRLUZLeFc2UUFB
  FIREBASE_API_KEY: QUl6YVN5QW9WN0hPX043d2ZaZW85ODhDZThsN0prMkd1M3FrSklF

---
# Web Deployment (Firebase Hosting)
apiVersion: v1
kind: ConfigMap
metadata:
  name: firebase-hosting-config
data:
  firebase.json: |
    {
      "hosting": {
        "public": "build/web",
        "ignore": [
          "firebase.json",
          "**/.*",
          "**/node_modules/**"
        ],
        "rewrites": [
          {
            "source": "**",
            "destination": "/index.html"
          }
        ],
        "headers": [
          {
            "source": "**/*.@(js|css|woff|woff2|ttf|otf)",
            "headers": [
              {
                "key": "Cache-Control",
                "value": "max-age=31536000"
              }
            ]
          }
        ]
      }
    }

---
# Docker Configuration for Server Deployments
apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectflow-web
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: projectflow-web
  template:
    metadata:
      labels:
        app: projectflow-web
    spec:
      containers:
      - name: projectflow
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web-content
          mountPath: /usr/share/nginx/html
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
        envFrom:
        - configMapRef:
            name: projectflow-config
        - secretRef:
            name: projectflow-secrets
      volumes:
      - name: web-content
        hostPath:
          path: /app/build/web
      - name: nginx-config
        configMap:
          name: nginx-config

---
apiVersion: v1
kind: Service
metadata:
  name: projectflow-service
  namespace: production
spec:
  selector:
    app: projectflow-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer